### ISSUE TITLE
8.a start a sprint

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#77]
A user can create a new sprint and assign a end time. The sprint which is created is automatically the current sprint. The sprint should not overlap with the current sprint. If the current sprint is still in progress the user should be asked whether it should be ended now (change the endtime) or whether the user want to cancel his action.

**Comment by PragTob** [comment]
Changed to a simple Start/Stop as with a stop watch for sprints. I I click start a new sprint is started, stop simply stops that one.

The start button isn't shown if there is a current sprint.

Planning sprints in advance is moved to another user story since for now it is too complicated and needs background job processing to work "properly".
